name:  Development
on: 
  push:
    branch:
    -  'main'
env:
  REPO_NAME: ranjanac
  env: dev
  APP_NAME: test-app
  IMAGE_NAME: test-image
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: set up Qemu
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
